### PR TITLE
Remove the oncompassneedscalibration event

### LINKED ISSUE #38: compassneedscalibration event - cannot confirm interoperability
Hello All,
Re:  https://w3c.github.io/deviceorientation/spec-source-orientation.html#compassneedscalibration

W3C staff has not been able to find any conforming implementation beyond IE.  At very least, it does not seem to make sense that support for this event be mandatory for implementations (which is what the current spec text requires).

This feature could remain in the spec, but it looks like it can only be optional given the lack of supporting implementations.  Since implementers monitor this repo, would like to hear feedback.

-Giri Mandyam, W3C Geolocation Working Group Chair

### PR DESCRIPTION
**Pull request by reillyeon**
There are no implementations of this event.

Fixed #38.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/107.html" title="Last updated on Mar 7, 2023, 12:57 AM UTC (7f1c214)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/107/7e1e1d9...7f1c214.html" title="Last updated on Mar 7, 2023, 12:57 AM UTC (7f1c214)">Diff</a>

### CODE REVIEW

**Comment by anssiko** [comment]
@diekus per https://caniuse.com/deviceorientation "`compassneedscalibration` event is supported in IE11 only for compatible devices with Windows 8.1+"

Can you or someone else from Microsoft confirm whether this caniuse.com information is accurate? Are you fine with the proposed removal?

**Comment by marcoscaceres** [comment]
Given that [IE is discontinued](https://learn.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-end-of-support), and [Windows 8.1 support ended on January 10, 2023](https://support.microsoft.com/en-us/windows/windows-8-1-support-ended-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93   
) it’s probably pretty safe to merge this.

**Comment by diekus** [comment]
Hola @anssiko , out of curiosity, what is the concern here with the event? There doesn't seem to be any implementation in Chromium nor other vendors.

I can confirm Chromium Edge does not implement this event.

**Comment by marcoscaceres** [comment]
The concern is basically the one you stated: no one implements it and so it could be removed from the spec. Otherwise, developers may try to rely on it etc.  

Removing it also simplifies the spec quite a bit.

**Review by anssiko — APPROVED** [review]

**Comment by anssiko** [comment]
Thanks @diekus! You were the only one implementing this feature so wanted to check with you.

@marcoscaceres I infer you're supportive of this removal from WebKit's point of view, correct?

**Comment by marcoscaceres** [comment]
That is correct. It would be great to remove it 🙏

**Comment by anssiko** [comment]
As a further evidence, we installed https://github.com/w3c/deviceorientation/pull/71 ~4 years ago to give a heads-up of a possible removal. I personally consider that an adequate time.

We are in fact in a similar situation with [`ondeviceorientationabsolute`](https://www.w3.org/TR/orientation-event/#deviceorientationabsolute).

**Comment by reillyeon** [comment]
[`ondeviceorientationabsolute`](https://www.w3.org/TR/orientation-event/#deviceorientationabsolute) is at least supported by Chromium-based browsers. According to our metrics usage is significantly lower than [`ondeviceorientation`](https://www.w3.org/TR/orientation-event/#deviceorientation) however as long as these APIs are used passively (without the site requesting permission) I don't trust these metrics to reflect how critical the API is to site functionality. Once we complete work on [Chromium issue 947112](https://crbug.com/947112) and have the ability to measure how often this feature is used with explicit user consent we will be able to make a more informed decision about whether the "absolute" version of these sensor events is important to developers.

**Pull request merged**
