### PR TITLE
update rotationRate alpha, beta, gamma description to be the same as implementation

### PR DESCRIPTION
**Pull request by juncaidf**
In the devicemotion specification:
https://w3c.github.io/deviceorientation/spec-source-orientation.html#devicemotion
The rotationRate: "It must be expressed as the rate of change of the angles defined in section 4.1"
So it means the rotation axes should be the following:
z axis: alpha
x axis: beta
y axis: gamma

However, Chrome on Android, Firefox browser on Android, and Safari browser on iPhone, they all implement rotationRate as the following:
x axis: alpha
y axis: beta
z axis: gamma

Given that this feature has been implemented in this way for a while and all the above browsers implement it in the same way which is different from the specification, updating the specification seems a better and easy solution. So this pull request updates the devicemotion specification's rotationRate alpha, beta, gamma description to be the same as implementation.

### CODE REVIEW

**Comment by andybloch** [comment]
I don't think it's a good idea to break a specification to match a broken implementation. Fix the implementation. Alpha is the rotation around the z axis for deviceorientation, and rotationRate should match it. The only question is whether the spec should be left as-is, or whether it should be replaced by renaming alpha-beta-gamma (maybe to Alpha-Beta-Gamma?) and the old names deprecated and redefined to match the broken implementation to avoid breaking existing code. Either way, it would take about 5 minutes to make this fix.

**Comment by anssiko** [comment]
Unless the implementations have changed since August 2017 (@juncaidf @reillyeon can you confirm), the proposal to make the spec reflect implementations seems reasonable.

Rationale: the feature has shipped for multiple years across multiple major browsers, all of them implementing the feature differently from the spec, and as defined in this PR. Changing the specification provides the path of least resistance and is aligned with [Priority of Constituencies](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies).

**Proposal**: merge this PR (after rebase).

Any concerns, please let us know.

**Comment by juncaidf** [comment]
The rotationRate alpha, beta, gamma implementations haven't changed since August 2017.

**Comment by andybloch** [comment]
The change you are proposing will make the definition of alpha, bet, and gamma different between devicemotion and deviceorientation. Don't do it. It breaks the specification and virtually ensures that there will be errors going forward by programmers who expect the definition to be the same and/or who know what alpha, beta, and gamma conventionally refer to.

Instead, browser developers should be encouraged to fix their browsers by deprecating the old names and replacing with new names that are less likely to be confused. New names should be adopted, such as "xDegrees", "yDegrees" and "zDegrees", for both devicemotion and deviceorientation. (Using x, y, and z in the name, instead of beta, gamma, and alpha, will reduce confusion. Using "degrees" in the name will make it clear that this is referring to a rotation, and that the unit is degrees, not radians.)  There should be a note in the specification saying the old names are deprecated because old browsers did not implement them correctly. (Also there should be a note that rotation rate on one axis can not be calculated from two successive deviceorientation measurements just on that one axis. To help avoid incorrect implementations, include the correct formulas.)

**Comment by reillyeon** [comment]
Deprecation of the old names in favor of new names is the plan of record. The only difference from your proposal is that the new names are part of a new API, [Gyroscope](https://w3c.github.io/gyroscope/), for which we have been careful to document and implement these angles correctly.

This specification and documentation (such as on MDN) will be updated to make a note of the intentional error in an effort to avoid developer confusion.

**Comment by reillyeon** [comment]
Discussed at Devices and Sensors WG Face-to-face at TPAC 2018. Agreed to accept this change (once merge conflicts have been resolved).

**Comment by anssiko** [comment]
@juncaidf @reillyeon can you rebase this?

**Comment by juncaidf** [comment]
Sure, I will rebase this.

**Comment by juncaidf** [comment]
@anssiko rebase completed, please review the change. Thanks!

**Comment by anssiko** [comment]
Thanks @juncaidf.

Merging per F2F resolution.

**Pull request merged**
