### PR TITLE
Convert Acceleration/RotationRate interfaces to dictionaries

### LINKED ISSUE #89: Convert DeviceMotionEventAcceleration/RotationRate to dictionaries
Currently they needlessly are interfaces.

* WebKit uses dictionaries for `acceleration`/`rotationRate`: https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/dom/DeviceMotionEvent.idl?rev=267813
* Gecko uses no-interface-object interfaces: https://searchfox.org/mozilla-central/rev/353f334d13359f7cb879b3cb38a94294231c2aa8/dom/webidl/DeviceMotionEvent.webidl

Blink currently is the only implementation that exposes the interfaces.

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes #89

***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/deviceorientation/pull/90.html" title="Last updated on Nov 16, 2020, 6:07 PM UTC (8afe268)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/90/b95751e...saschanaz:8afe268.html" title="Last updated on Nov 16, 2020, 6:07 PM UTC (8afe268)">Diff</a>

### CODE REVIEW

**Comment by anssiko** [comment]
Thanks, given Blink currently is the only implementation that exposes the interfaces (per #89), I'll defer to @reillyeon to understand web compat implications (I did not see any UseCounters in Blink that'd help here, but maybe I overlooked something).

I could imagine some existing web content might feature test against these interfaces, but I'd like to see some data on that.

**Comment by mkruisselbrink** [comment]
Per WebIDL attributes can not be dictionary types. As this seems to be changing the types of various attributes in DeviceMotionEvent to a dictionary, the result of that is invalid IDL.

(see https://heycam.github.io/webidl/#idl-attributes:

> The type of the attribute, after resolving typedefs, must not be a nullable or non-nullable version of any of the following types: [...] a dictionary type

**Comment by saschanaz** [comment]
> Per WebIDL attributes can not be dictionary types. As this seems to be changing the types of various attributes in DeviceMotionEvent to a dictionary, the result of that is invalid IDL.
> 
> (see https://heycam.github.io/webidl/#idl-attributes:
> 
> > The type of the attribute, after resolving typedefs, must not be a nullable or non-nullable version of any of the following types: [...] a dictionary type

Oh that's true! Sorry for bothering you, I'll file an issue at Web IDL instead.

**Comment by saschanaz** [comment]
Okay, dictionaries are copied and thus not very good for attributes (`ev.acceleration === ev.acceleration` will return false), closing.

**Pull request closed without merging**
