### PR TITLE
add security and privacy section

### PR DESCRIPTION
**Pull request by timvolodine**
to address issue https://github.com/w3c/deviceorientation/issues/24

### CODE REVIEW

**Comment by maryammjd** [comment]
@timvolodine

**Comment by richtr** [comment]
https://github.com/w3c/deviceorientation/pull/25/files#diff-87104462239df473f9aa72c3bb6ad124R641:
> fire events only on the top-level browsing context or same-origin nested iframes

Should this be an 'and'? We should try to recommend a single idea here for compatibility purposes.

**Comment by martinthomson** [comment]
Why not restrict this to [secure contexts](https://w3c.github.io/webappsec/specs/powerfulfeatures/) instead?  That has a robust definition.  I don't see it as actually helping with the problems that this describes, but the definition is precise enough for this.

**Comment by maryammjd** [comment]
@timvolodine 
The security discussion is nice, however the security and privacy risks associated with this issue are more than fingerprinting the mobile devices. As we discussed it with the W3C Geolocation Working Group via emails, our [paper](http://www.sciencedirect.com/science/article/pii/S2214212615000678) (published in the Journal of Information Security and Applications) shows that these sensor measurements can reveal the user's PINs. It is worth mentioning this level of security risks in the security consideration section. 

-Maryam (m.mehrnezhad@ncl.ac.uk)

**Comment by maryammjd** [comment]
Free link to the paper: 
http://arxiv.org/abs/1602.04115

**Comment by timvolodine** [comment]
okay I think I've addressed all comments, in particular
- added secure contexts
- added reference to the paper

I'll merge if there are no objections :)

**Pull request merged**
