### PR TITLE
editorial: Identify at risk features and their causes

### PR DESCRIPTION
**Pull request by reillyeon**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/149.html" title="Last updated on Mar 13, 2024, 5:51 PM UTC (7e1cef8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/149/1d42f14...7e1cef8.html" title="Last updated on Mar 13, 2024, 5:51 PM UTC (7e1cef8)">Diff</a>

### CODE REVIEW

**Comment by reillyeon** [comment]
@anssiko and @marcoscaceres, please take a look.

**Review by anssiko — APPROVED** [review]
@reillyeon this looks good to me, thanks!

@himorin can we keep these inline or do we need to pull them up to SOTD to pass checkers etc.? I personally feel keeping these inline is better to retain context.

**Comment by himorin** [comment]
I believe both (having or not having in SoTD) should be fine. [One example](https://www.w3.org/TR/vc-data-model-2.0/#refreshing) for not having.
at-risk is [MAY in process](https://www.w3.org/2023/Process-20231103/#at-risk), and no strict text is provided in [pubrules](https://www.w3.org/pubrules/doc/rules/?profile=CR#featAtRisk).

**Comment by reillyeon** [comment]
@marcoscaceres, can you take a look?

**Review by marcoscaceres — APPROVED** [review]
That's great. Thanks!

**Pull request merged**
