### PR TITLE
Add the ondeviceorientationabsolute event handler attribute

### PR DESCRIPTION
**Pull request by foolip**
This is already in Blink's IDL:
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/device_orientation/WindowDeviceOrientation.idl

### CODE REVIEW

**Comment by foolip** [comment]
This was overloooked in https://github.com/w3c/deviceorientation/pull/31

**Comment by foolip** [comment]
Ping @timvolodine

**Comment by timvolodine** [comment]
hmm, I think it's already in the 'deviceorientationabsolute' section, i.e.
https://www.w3.org/TR/orientation-event/#deviceorientationabsolute

"[..] User agents must also provide an event handler IDL attribute [HTML5] named ondeviceorientationabsolute on the window object. [..]"

**Comment by foolip** [comment]
For `ondevicemotion` there's both that bit of prose and an IDL block, so I was going for that. Just the IDL block should suffice too, but the redundancy is harmless I think.

**Comment by ashimura** [comment]
+1 :)

**Comment by plehegar** [comment]
For what is worth, only Chrome seems to support this event type.

**Comment by anssiko** [comment]
@foolip, what is the current implementation status of this `ondeviceorientationabsolute` event across implementation beyond Chrome?

We're restarting this work and cleaning up the PR queue and would like to get the latest data to allow the group to make an informed decision.

**Comment by foolip** [comment]
@anssiko per http://web-confluence.appspot.com/#!/catalog?q="ondeviceorientationabsolute" it's still Chrome-only. But that presumably goes for the event itself as well, not just the event handler attribute.

**Comment by reillyeon** [comment]
According to https://www.chromestatus.com/metrics/feature/popularity usage of `deviceorientationabsolute` is very low. That could be enough to consider depreciation in Chrome if no other implementation has picked it up. Are the `deviceorientation` events fired by other implementations based on an absolute reference frame?

**Comment by foolip** [comment]
> Are the `deviceorientation` events fired by other implementations based on an absolute reference frame?

I haven't done any testing, but in https://groups.google.com/a/chromium.org/d/msg/blink-dev/lT_-2CiHOf4/UEpwwtdvAgAJ it was said that Safari's are relative by default. `deviceorientationabsolute` was added so that there would be a way to get the old behavior as Chrome changed to match Safari here.

**Comment by reillyeon** [comment]
Discussed at Devices and Sensors WG Face-to-face at TPAC 2018. If Chrome keeps this event then this PR should be modified to add a non-normative note about the additional event available in some user agents. If Chrome deprecates then this can be closed without merging.

**Comment by foolip** [comment]
The deviceorientationabsolute event is already described in normative terms in the spec and this is just added the missing event handler attribute, not the firing of the event itself.

I think the options would be to delete everything about deviceorientationabsolute from the spec and perhaps leave a non-normative note, or to merge this PR. Things are now in an inconsistent state, so change does not seem like a good option regardless of the fate of the event.

**Comment by reillyeon** [comment]
Apologies for my misunderstanding. I agree then that merging this PR is the best option to bring the spec into a consistent state. It is then a separate issue to add non-normative text describing the current implementation status.

**Comment by reillyeon** [comment]
I have rebased @foolip's change.

**Comment by anssiko** [comment]
Given this PR adds the missing IDL for `ondeviceorientationabsolute` to complement its existing normative prose, I expect no concerns in merging this PR. This is technically almost an editorial change.

However, if any concerns are raised, please let us know and we'll re-open this discussion.

A separate issue is to add non-normative text describing the current implementation status.

**Comment by anssiko** [comment]
(Opened issue #60 for the non-normative text.)

**Pull request merged**
